name: Version update pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - release
      - feature

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Run Python script
        run: |
          python .github/workflows/script.py patch

      - name: Configure Git
        run: |
          git config --global user.email "artemalesin89778@gmail.com"
          git config --global user.name "trench-live"

      - name: Commit and push changes
        run: |
          git add version version_log
          git commit -m "Update version and log"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: (TST)
    needs: run-script
    uses: trench-live/devops_control_point_1/.github/workflows/test.yml@release
    with:
      version: alpha